# Generated by Django 4.0.1 on 2022-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0002_remove_profile_projects_project_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='average_review',
            field=models.IntegerField(default=0),
        ),
    ]
